#!/usr/bin/env python3
"""Generate tests/hardware/div_edges.asm: DIV/IDIV r8/r16/r32 against the
486's rules (quotient range, truncation toward zero, remainder sign, #DE for
overflow or a zero divisor). Each case sets the dividend and divisor, divides,
and compares AX/DX (or EAX/EDX) and whether INT 0 fired with the expected
values; the first mismatch reports its case number in EBP.
Usage: make_div_edges.py OUT.asm [random-count]"""
import random
import sys


def trunc_div(a, b):
    q = abs(a) // abs(b)
    return q if (a >= 0) == (b >= 0) else -q


def expect(op, bits, dividend, divisor):
    """Return (fault, quotient, remainder) as unsigned register values."""
    mask = (1 << bits) - 1
    if divisor == 0:
        return True, 0, 0
    if op == 'div':
        q, r = divmod(dividend, divisor)
        if q > mask:
            return True, 0, 0
        return False, q, r
    # signed: dividend is 2*bits wide, divisor bits wide
    a = dividend - (1 << (2 * bits)) if dividend >> (2 * bits - 1) else dividend
    b = divisor - (1 << bits) if divisor >> (bits - 1) else divisor
    q = trunc_div(a, b)
    r = a - q * b
    if not -(1 << (bits - 1)) <= q <= (1 << (bits - 1)) - 1:
        return True, 0, 0
    return False, q & mask, r & mask


def cases(n_random, rng):
    out = []
    edges = {
        8: [0, 1, 2, 0x7f, 0x80, 0x81, 0xfe, 0xff],
        16: [0, 1, 2, 3, 0x7fff, 0x8000, 0x8001, 0xfffe, 0xffff, 0x100],
        32: [0, 1, 2, 3, 0x7fffffff, 0x80000000, 0x80000001, 0xfffffffe, 0xffffffff, 0x10000],
    }
    for bits in (8, 16, 32):
        m = (1 << bits) - 1
        # dividends near the quotient limits for the edge divisors
        for op in ('div', 'idiv'):
            for d in edges[bits]:
                for q in (1, (1 << (bits - 1)) - 1, 1 << (bits - 1), m, m + 1):
                    for r in (0, (d - 1) & m if d else 0):
                        a = (q * (d if d else 1) + r) & ((1 << 2 * bits) - 1)
                        out.append((op, bits, a, d))
                        # the signed mirror: -(q*d) (+/- remainder)
                        out.append((op, bits, (-a) & ((1 << 2 * bits) - 1), d))
        for _ in range(n_random):
            op = rng.choice(('div', 'idiv'))
            d = rng.choice(edges[bits] + [rng.getrandbits(bits)] * 4)
            if rng.random() < 0.5:
                a = rng.getrandbits(2 * bits)
            else:  # keep the quotient in range most of the time
                a = (rng.getrandbits(bits) * (d or 1) + rng.getrandbits(max(1, bits - 1))) & ((1 << 2 * bits) - 1)
                if rng.random() < 0.5:
                    a = (-a) & ((1 << 2 * bits) - 1)
            out.append((op, bits, a, d))
    # unique, stable order
    seen, uniq = set(), []
    for c in out:
        if c not in seen:
            seen.add(c)
            uniq.append(c)
    return uniq


def main():
    path = sys.argv[1]
    n_random = int(sys.argv[2]) if len(sys.argv) > 2 else 300
    rng = random.Random(486)
    L = ['; SPDX-License-Identifier: GPL-3.0-or-later',
         '; Generated by tests/make_div_edges.py: DIV/IDIV edge cases (see there).',
         '        cpu     486', '        org     100h', 'bits 16',
         'start:  cli', '        cld', '        mov     ax, cs', '        mov     ds, ax',
         '        mov     ss, ax', '        mov     sp, 0FFF0h',
         '        xor     ax, ax', '        mov     es, ax',
         '        mov     word [es:0], de_handler', '        mov     [es:2], cs',
         '        mov     ebp, 0', '        jmp     cases',
         '; #DE: IP points at the faulting DIV/IDIV (2 bytes, 3 with 66h); skip it.',
         'de_handler:',
         '        push    bp', '        mov     bp, sp', '        push    si', '        push    ds',
         '        mov     si, [bp+2]', '        mov     ds, [bp+4]',
         '        cmp     byte [si], 66h', '        jne     .two', '        inc     word [bp+2]',
         '.two:   add     word [bp+2], 2', '        pop     ds', '        pop     si',
         '        mov     byte [cs:faulted], 1', '        pop     bp', '        iret',
         'faulted: db 0',
         'fail:   mov     dx, 7FE4h', '        mov     ax, 0BADh', '        out     dx, ax',
         '        hlt', '        jmp     $',
         'cases:']
    for n, (op, bits, a, d) in enumerate(cases(n_random, rng)):
        fault, q, r = expect(op, bits, a, d)
        L.append(f'; case {n}: {op} r{bits} {a:#x} / {d:#x} -> '
                 + ('#DE' if fault else f'q={q:#x} r={r:#x}'))
        L.append(f'        mov     ebp, {n}')
        L.append('        mov     byte [faulted], 0')
        if bits == 8:
            L += [f'        mov     ax, {a:#x}', f'        mov     cl, {d:#x}', f'        {op}     cl']
            check = ([] if fault else
                     [f'        cmp     al, {q:#x}', '        jne     fail',
                      f'        cmp     ah, {r:#x}', '        jne     fail'])
        elif bits == 16:
            L += [f'        mov     ax, {a & 0xffff:#x}', f'        mov     dx, {a >> 16:#x}',
                  f'        mov     cx, {d:#x}', f'        {op}     cx']
            check = ([] if fault else
                     [f'        cmp     ax, {q:#x}', '        jne     fail',
                      f'        cmp     dx, {r:#x}', '        jne     fail'])
        else:
            L += [f'        mov     eax, {a & 0xffffffff:#x}', f'        mov     edx, {a >> 32:#x}',
                  f'        mov     ecx, {d:#x}', f'        {op}     ecx']
            check = ([] if fault else
                     [f'        cmp     eax, {q:#x}', '        jne     fail',
                      f'        cmp     edx, {r:#x}', '        jne     fail'])
        L += [f'        cmp     byte [faulted], {1 if fault else 0}', '        jne     fail'] + check
    L += ['        mov     dx, 7FF0h', '        mov     ax, 600Dh', '        out     dx, ax',
          '        hlt', '        jmp     $']
    open(path, 'w', newline='\n').write('\n'.join(L) + '\n')
    print(len(cases(n_random, random.Random(486))), 'cases')


main()
